### ISSUE TITLE
加载到burp时报错

### ISSUE THREAD

**Issue by jinzezhi** [yxw21/xssbughunter#1]
![image](https://user-images.githubusercontent.com/93123422/216227639-ea1fc644-df3a-4e02-a385-bcde0985c6e5.png)
师傅可以帮忙看下是什么问题吗

**Comment by yxw21** [comment]
# Minimum Burp Suite Version

2023.1

Because of the use of Burp Extensions API - Montoya

**Comment by jinzezhi** [comment]
> # Minimum Burp Suite Version
> 2023.1
> 
> Because of the use of Burp Extensions API - Montoya

I don't quite understand what you mean.  My version is 2022.8, do I need to update it

**Comment by yxw21** [comment]
yes
